name: test before merging into master

on:
  pull_request:
    branches:
      - "feature/**"
      - "fix/**"
      - "hotfix/**"
      - "release/v**}"

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [macos-10.15]
        node: [12.x]
    runs-on: ${{ matrix.os }}
    environment: staging_environment
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      # https://qiita.com/qualitia_cdev/items/407b0df9c0a0f0f45bbc
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: Run test
        run: yarn test:ci
